sudo: required
dist: trusty
os: linux
language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "sa-east-1"
    app: "ethereum-blockchain-indexer"
    env: "ethereum-blockchain-indexer-dev"
    bucket_name: "elasticbeanstalk-sa-east-1-869739316835"
    on:
      branch: develop
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "ethereum-blockcain-indexer"
    region: "sa-east-1"
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on:
      branch: develop
      repo: bloqpriv/ethereum-blockchain-indexer
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket_name: "ethereum-blockcain-indexer"
    region: "sa-east-1"
    key: indexer-latest.zip
    bundle_type: zip
    application: ethereum-blockchain-indexer-parser-dev
    deployment_group: Metronome
    on:
      branch: develop
      repo: bloqpriv/ethereum-blockchain-indexer

script:
  - zip -r indexer-latest *
  - mkdir -p dpl_cd_upload
  - mv indexer-latest.zip dpl_cd_upload/indexer-latest.zip